### ISSUE TITLE
Switch docker image from flask only to uwsgi-nginx-flask

### ISSUE THREAD

**Issue by hbruch** [osmoscope/osmoscope-server#2]
Flask should not be run as standalone server in production.

Switching to uwsgi-nginx-flask would allow to run the container standalone.

However, as the server is not started directly via main.py any longer, the layer update job scheduled on server launch now has to be started differently. 

Options I currently see:

1.  a background python process is started, e.g. via /app/prestart.sh.
2. a cronjob is registered 

@tommyjcarpenter in branch [nginx](https://github.com/osmoscope/osmoscope-server/tree/nginx), I started switching to uwsgi-nginx-flask. For now I prefer not to nest the application below app/app folders, and tests, setup, too are missing, too. Anyhow, feel free to comment :-)

**Comment by tommyjcarpenter** [comment]
I'm not sure if their container works without the nesting unless you configure the uwsgi stuff appropriately? I've never tried to get their container to work without their expected structure.

**Comment by hbruch** [comment]
Closed via c2f1665
